[package]
name = "sender"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs", "io-util"] }
tokio-stream = "0.1"
tonic = "0.11"
prost = "0.12"
async-stream = "0.3"

[build-dependencies]
tonic-build = "0.11"
